# 2. Các kiểu dữ liệu trong Python

In [13]:
x = 10        # int
y = 3.14      # float
z = 1 + 2j    # complex
print(type(x), type(y), type(z))

<class 'int'> <class 'float'> <class 'complex'>


In [14]:
name = "Python"
print(name, type(name))

Python <class 'str'>


In [15]:
fruits = ["apple", "banana", "cherry"]
print(fruits, type(fruits))

['apple', 'banana', 'cherry'] <class 'list'>


In [16]:
coordinates = (10, 20, 30)
print(coordinates, type(coordinates))

(10, 20, 30) <class 'tuple'>


In [17]:
unique_numbers = {1, 2, 3, 4}
print(unique_numbers, type(unique_numbers))

{1, 2, 3, 4} <class 'set'>


In [18]:
student = {"name": "John", "age": 20}
print(student, type(student))

{'name': 'John', 'age': 20} <class 'dict'>


In [19]:
is_active = True
print(is_active, type(is_active))

True <class 'bool'>


In [20]:
data = None
print(data, type(data))

None <class 'NoneType'>


# 3. Cách khai báo biến

In [21]:
x = 10  # Biến nguyên
name = "Python"  # Biến chuỗi
is_active = True  # Biến logic

# 4. Các phép tính và toán tử cơ bản

In [22]:
a = 5
b = 3
print(a + b)  # Kết quả: 8

8


In [23]:
a = 5
b = 3
print(a - b)  # Kết quả: 2

2


In [24]:
a = 5
b = 3
print(a * b)  # Kết quả: 15

15


In [25]:
a = 5
b = 2
print(a / b)  # Kết quả: 2.5

2.5


In [26]:
a = 5
b = 2
print(a // b)  # Kết quả: 2

2


In [27]:
a = 5
b = 2
print(a % b)  # Kết quả: 1

1


In [28]:
a = 2
b = 3
print(a ** b)  # Kết quả: 8

8


# 5. Các câu điều kiện và vòng lặp

In [29]:
x = 10
if x > 5:
    print("x lớn hơn 5")
elif x == 5:
    print("x bằng 5")
else:
    print("x nhỏ hơn 5")

x lớn hơn 5


In [30]:
for i in range(5):
    print(i)

0
1
2
3
4


In [31]:
x = 0
while x < 5:
    print(x)
    x += 1

0
1
2
3
4


# 6. Ví dụ giải phương trình bậc 2

In [32]:
import math

def solve_quadratic(a, b, c):
    # Tính địa
    delta = b**2 - 4*a*c
    if delta < 0:
        return "Phương trình vô nghiệm"
    elif delta == 0:
        x = -b / (2*a)
        return f"Phương trình có nghiệm kép: x = {x}"
    else:
        x1 = (-b + math.sqrt(delta)) / (2*a)
        x2 = (-b - math.sqrt(delta)) / (2*a)
        return f"Phương trình có hai nghiệm: x1 = {x1}, x2 = {x2}"

# Ví dụ
print(solve_quadratic(1, -3, 2))

Phương trình có hai nghiệm: x1 = 2.0, x2 = 1.0


# 7. List trong Python

In [1]:
# Tạo danh sách
my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]


In [2]:
# Truy cập phần tử đầu tiên
print(my_list[0])

# Truy cập phần tử cuối cùng
print(my_list[-1])

1
5


In [3]:
# Thêm phần tử vào danh sách
my_list.append(6)  # Thêm vào cuối
my_list.insert(2, 10)  # Chèn vào vị trí index 2
print(my_list)

# Xóa phần tử
my_list.remove(10)  # Xóa giá trị 10
print(my_list)

[1, 2, 10, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [4]:
# Duyệt danh sách bằng vòng lặp for
for item in my_list:
    print(item)

1
2
3
4
5
6


In [6]:
# Tạo danh sách mới từ danh sách cũ
squared_list = [x**2 for x in my_list]
print(squared_list)

[1, 4, 9, 16, 25, 36]


# 8. Array trong Python

In [7]:
# Tạo một danh sách (list) trong Python
arr = [1, 2, 3, 4, 5]
print(arr)

[1, 2, 3, 4, 5]


In [8]:
import array

# Tạo một mảng số nguyên
arr = array.array('i', [1, 2, 3, 4, 5])
print(arr)

array('i', [1, 2, 3, 4, 5])


# 9. Array trong Numpy

In [10]:
import numpy as np

# Tạo một mảng NumPy từ danh sách Python
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [11]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

# Lấy kích thước của mảng
print("Shape:", matrix.shape)

# Truy cập phần tử
print("Phần tử hàng 1, cột 2:", matrix[0, 1])

# Thực hiện phép toán
arr2 = arr * 2  # Nhân mỗi phần tử với 2
print(arr2)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Phần tử hàng 1, cột 2: 2
[ 2  4  6  8 10]


In [12]:
# Cộng hai ma trận
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print("Ma trận tổng:\n", C)

# Nhân hai ma trận
D = np.dot(A, B)
print("Ma trận tích:\n", D)

# Tính ma trận chuyển vị
E = A.T
print("Ma trận chuyển vị:\n", E)

# Tính định thức
det_A = np.linalg.det(A)
print("Định thức của A:", det_A)

# Tính ma trận nghịch đảo
inv_A = np.linalg.inv(A)
print("Ma trận nghịch đảo của A:\n", inv_A)

Ma trận tổng:
 [[ 6  8]
 [10 12]]
Ma trận tích:
 [[19 22]
 [43 50]]
Ma trận chuyển vị:
 [[1 3]
 [2 4]]
Định thức của A: -2.0000000000000004
Ma trận nghịch đảo của A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 10. Array trong pandas

In [13]:
import pandas as pd

# Tạo Series từ danh sách
series = pd.Series([1, 2, 3, 4, 5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [14]:
# Tạo DataFrame từ danh sách
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df = pd.DataFrame(data)
print(df)

   A  B
0  1  4
1  2  5
2  3  6


In [15]:
# Truy cập cột 'A'
print(df['A'])

# Truy cập hàng đầu tiên
print(df.iloc[0])

0    1
1    2
2    3
Name: A, dtype: int64
A    1
B    4
Name: 0, dtype: int64


In [ ]:
# Đọc file CSV
csv_df = pd.read_csv("data.csv")
print(csv_df.head())

# Đọc file Excel
excel_df = pd.read_excel("data.xlsx", sheet_name="Sheet1")
print(excel_df.head())